# Homebrew formula for lyrics-tool (macOS + Linuxbrew).
#
# This installs the package and its Python dependencies into an isolated
# virtualenv under the Cellar, so it never touches the system site-packages.
#
# To finalise for a tap:
#   1. Publish to PyPI (or point `url` at the GitHub release tarball).
#   2. Update `url` + `sha256` (`brew fetch` prints the sha).
#   3. Optionally pin each dependency with `resource` blocks generated by
#      `brew update-python-resources Formula/lyrics-tool.rb`.
class LyricsTool < Formula
  include Language::Python::Virtualenv

  desc "Cross-platform terminal lyrics visualizer and LRC/WLRC toolkit"
  homepage "https://github.com/hamza-abdelmoumene/lyrics-tool"
  url "https://github.com/hamza-abdelmoumene/lyrics-tool/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "REPLACE_WITH_RELEASE_TARBALL_SHA256"
  license "MIT"

  depends_on "python@3.12"
  # Optional but recommended: live now-playing on macOS.
  depends_on "nowplaying-cli" => :optional

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "usage", shell_output("#{bin}/lyricsooo --help")
    assert_match "usage", shell_output("#{bin}/lyricsooo-fetch --help")
  end
end
